{
    'name': 'Smart Attendance',
    'version': '2.0.0',
    'summary': 'Module for managing attendance.',
    'description': 'Smart Attendance module, with features for tracking and managing employee attendance.',
    'category': 'Tools',
    'author': 'Sel Studio',
    'website': 'https://selstudio.id',
    'depends': ['base', 'web', 'hr', 'hr_attendance', 'resource'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/attendance_views.xml',
        'views/employee_views.xml',
        'views/department_views.xml',
        'views/job_views.xml',
        'views/work_location_views.xml',
        'views/working_schedule_views.xml',
        'views/dashboard_views.xml', 
        'views/menu_views.xml',
        'views/templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
            'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',
            'https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css',
            'https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js',
            'hr_smartatt/static/src/css/styles.css',
            'hr_smartatt/static/src/components/LoginForm.js',
            'hr_smartatt/static/src/components/BottomBar.js',  
            'hr_smartatt/static/src/components/Account.js',  
            'hr_smartatt/static/src/components/Dashboard.js',
            'hr_smartatt/static/src/components/AttendanceHistory.js',
            'hr_smartatt/static/src/app.js',
        ],
        'web.assets_backend': [
            'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
            'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',
            'hr_smartatt/static/src/js/location_picker_widget.js',
            'hr_smartatt/static/src/xml/location_picker_template.xml',
            'hr_smartatt/static/src/css/backend.css',
            'hr_smartatt/static/src/admin_dashboard/dashboard.js',
            'hr_smartatt/static/src/admin_dashboard/dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'sequence': 1,
}